# 指定局部路径规划器插件 —— 使用 DWA（动态窗口法）
base_local_planner: dwa_local_planner/DWAPlannerROS

# DWA 局部规划器的具体参数配置
DWAPlannerROS:



  # —————— 加速度限制（单位：m/s² 或 rad/s²） ——————
  # X方向（前进/后退）最大加速度。值太大会导致急加速，不安全；太小则响应迟钝。
  acc_lim_x: 1
  # Y方向（横向）最大加速度。差速机器人通常不支持横向移动，设为 0.0
  acc_lim_y: 0.0
  # 旋转角加速度最大值（绕Z轴）。影响转弯响应速度，太大易打滑或震荡。
  acc_lim_theta: 5



  # —————— 速度限制（单位：m/s 或 rad/s） ——————
  # 前进方向最大速度（正向）
  max_vel_x: 0.3
  # 前进方向最小速度（允许倒车时可设为负值，此处禁止倒车）
  min_vel_x: -0.3
  # 横向最大/最小速度（差速模型不支持横向移动，设为 0.0）
  max_vel_y: 0.0
  min_vel_y: 0.0
  # 最大旋转角速度（顺时针/逆时针）
  max_vel_theta: 0.3
  # 最小旋转角速度（负值表示允许反向旋转）
  min_vel_theta: -0.3

  # —————— 采样参数 ——————
  # 在速度空间中对线速度 vx 的采样点数。越多越精细但计算量越大。
  vx_samples: 128
  # 对角速度 vtheta 的采样点数。通常比 vx 多，因为旋转对避障更敏感。
  vtheta_samples: 128

  # —————— 轨迹仿真与评分参数 ——————
  # 仿真时长（秒）：DWA 会预测每个采样速度在未来 sim_time 秒内的轨迹
  sim_time: 3
  # 路径跟踪权重：值越大，越走中间
  path_distance_bias: 64
  # 目标接近权重：值越大，越有前进动力
  goal_distance_bias: 64
  # 障碍物距离惩罚权重：值越大，越害怕靠近障碍物（安全第一）
  # 注意：该值通常较小（如0.01），因为障碍物代价地图本身已具高惩罚
  occdist_scale: 0



  # —————— 调试与可视化 ——————
  # 是否发布采样的候选轨迹点云（用于 RViz 可视化调试）
  publish_traj_pc: true
  # 是否发布代价地图的评分网格点云（用于分析路径评分分布）
  publish_cost_grid_pc: true

  # —————— 行为控制参数 ——————
  # 朝向目标点的“预瞄距离”（米）：用于计算朝向评分，值太小易震荡，太大反应迟钝
  heading_lookahead: 2
  # 震荡复位距离（米）：机器人移动超过此距离后，才允许解除“震荡锁定”状态
  oscillation_reset_dist: 0.05
  # 是否在机器人前进时“裁剪”已通过的全局路径点（推荐 true，避免路径回溯）
  prune_plan: true