# ========== move_base 核心行为参数 ==========

# 是否在 move_base 进入非活动状态（如空闲或目标到达）时关闭代价地图以节省资源
# false = 始终保持代价地图运行（推荐，避免重新激活时初始化延迟）
# true = 空闲时关闭，激活时重建（节省CPU但可能导致响应延迟）
shutdown_costmaps: false

# 局部控制器（如 DWA）的运行频率（Hz）
# 控制器每秒计算并发布速度指令的次数。值越高，运动控制越平滑，但计算负载越大。
# 通常 5~20 Hz；10.0 Hz 是平衡性能与响应的常用值
controller_frequency: 10.0

# 局部控制器在“无法找到有效路径”时的最大等待时间（秒）
# 若局部规划器持续失败超过此时间，将触发恢复行为（如旋转、清空代价地图）
# 设置太短易频繁触发恢复；太长则卡死不处理。5.0 秒是合理默认值
controller_patience: 20.0

# 全局路径规划器的重规划频率（Hz）—— 当启用动态重规划时生效
# 注意：若 GlobalPlanner 中也设置了 planner_frequency，以 move_base 此处为准
# 设为 0 表示仅在需要时（如局部失败或目标更新）才重规划
# 1.0 Hz 表示每秒最多尝试重新规划一次全局路径
planner_frequency: 1.0

# 全局规划器在“无法找到有效路径”时的最大等待时间（秒）
# 若全局规划持续失败超过此时间，将触发恢复行为或报错
# 与 controller_patience 配合使用，5.0 秒是安全默认值
planner_patience: 20.0

# 震荡行为检测超时时间（秒）
# 若机器人在 oscillation_distance 范围内来回移动的时间超过此值，视为“震荡”
# 触发震荡恢复行为（如后退、旋转）以脱困
oscillation_timeout: 10.0

# 震荡检测的距离阈值（米）
# 机器人位置变化小于此距离，且持续 oscillation_timeout 时间，判定为震荡
# 0.2m 适用于中小型室内机器人；大型或室外机器人可适当增大（如 0.5m）
oscillation_distance: 0.05